# Generated by Django 3.2 on 2021-07-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0002_auto_20210720_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('image', models.ImageField(null=True, upload_to='static/media')),
            ],
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
