# Generated by Django 3.2 on 2021-07-22 09:20

from django.db import migrations, models
import django_matplotlib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0003_auto_20210720_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', django_matplotlib.fields.MatplotlibFigureField()),
            ],
        ),
    ]
