# Generated by Django 3.2 on 2021-07-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0004_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
