# Generated by Django 3.2 on 2021-07-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0005_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race_CSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('asian', models.IntegerField(max_length=15)),
                ('black', models.IntegerField(max_length=15)),
                ('white', models.IntegerField(max_length=15)),
                ('total', models.IntegerField(max_length=15)),
                ('incident', models.IntegerField(max_length=10)),
                ('inc_rate', models.IntegerField(max_length=15)),
                ('a_rate', models.IntegerField(max_length=15)),
                ('b_rate', models.IntegerField(max_length=15)),
                ('w_rate', models.IntegerField(max_length=15)),
            ],
        ),
    ]
