# Generated by Django 3.2 on 2021-07-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0006_race_csv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Race_CSV',
        ),
    ]
